#!/bin/bash

set -ex

APT_PACKAGES=(
    # Useful system packages
    build-essential
    curl
    git
    snapd
    # Packages needed/nice-to-have to run workshops
    chromium-browser
    scratch
    python3
    ruby
)

sudo apt update -y
sudo apt upgrade -y
sudo apt install -y "${APT_PACKAGES[@]}"

# Install Atom
sudo snap install atom --classic
